# Generated by Buildr 1.4.6, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "com.jeffplaisance"
COPYRIGHT = "Copyright 2011 Jeff Plaisance"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2" << "http://repo1.maven.org/maven2"

desc "The Serialization project"
define "serialization" do
  project.no_ipr
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with 'com.google.guava:guava:jar:r09', 'org.apache.commons:commons-lang3:jar:3.1', 'args4j:args4j:jar:2.0.16', 'org.functionaljava:functionaljava:jar:3.0' # Add classpath dependencies
  package(:jar)
end
